const mapPaises = {
    "argentina": "🇦🇷",
    "brasil": "🇧🇷",
    "brazil": "🇧🇷",
    "españa": "🇪🇸",
    "spain": "🇪🇸",
    "uruguay": "🇺🇾",
    "chile": "🇨🇱",
    "paraguay": "🇵🇾",
    "bolivia": "🇧🇴",
    "colombia": "🇨🇴",
    "venezuela": "🇻🇪",
    "ecuador": "🇪🇨",
    "peru": "🇵🇪",
    "perú": "🇵🇪",
    "mexico": "🇲🇽",
    "méxico": "🇲🇽",
    "estados unidos": "🇺🇸",
    "usa": "🇺🇸",
    "inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "francia": "🇫🇷",
    "france": "🇫🇷",
    "italia": "🇮🇹",
    "italy": "🇮🇹",
    "alemania": "🇩🇪",
    "germany": "🇩🇪",
    "portugal": "🇵🇹",
    "holanda": "🇳🇱",
    "netherlands": "🇳🇱",
    "paises bajos": "🇳🇱",
    "países bajos": "🇳🇱",
    "croacia": "🇭🇷",
    "croatia": "🇭🇷",
    "marruecos": "🇲🇦",
    "morocco": "🇲🇦",
    "japon": "🇯🇵",
    "japón": "🇯🇵",
    "japan": "🇯🇵",
    "corea del sur": "🇰🇷",
    "south korea": "🇰🇷",
    "senegal": "🇸🇳",
    "camerun": "🇨🇲",
    "camerún": "🇨🇲",
    "cameroon": "🇨🇲",
    "ghana": "🇬🇭",
    "canada": "🇨🇦",
    "canadá": "🇨🇦",
    "merlo": "🟤"
};

export default function obtenerEmojiPais(pais) {
    if (!pais || typeof pais !== 'string') return "🌎";
    const normalized = pais.trim().toLowerCase();
    return mapPaises[normalized] || "🌎";
}
